# Generated by Django 5.2.5 on 2025-09-02 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('gram_panchayat', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('shg_code', models.CharField(max_length=50)),
                ('shg_name', models.CharField(max_length=200)),
                ('member_code', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('marital_status', models.CharField(choices=[('Unmarried', 'Unmarried'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=50)),
                ('disability_status', models.BooleanField(default=False)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('expertise', models.TextField()),
                ('training_history', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(help_text='e.g. Weekdays, Weekends', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
