# Generated by Django 5.2.5 on 2025-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_villageorganizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='temp_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mastertrainer',
            name='temp_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
